import React from "react";

import { Switch, Redirect } from "react-router-dom";
import { RouteWithLayout } from "./Components";

import {
  HomePage,
  AboutPage,
  BlogPage,
  ContactPage,
  TeamPage,
  GalleryPage,
  ServicesPage,
  AccessoriesPage,
  EdesignPage,
  LogoDevPage,
  BusinessPage,
  StickerPage,
  BannerPage,
  
 
  FlexPage,
  DigitalBrandPage,
  ConsultationPage,
  MaintenancePage,
  InternetPage,
  SocialPage,
  ColorPage,
  ContentPage,
  ClothingPage,
  SystemAnaPage,
  BusinessAnaPage,
  RiskManPage,
  QualityAssPage,
  ProjectManPage,
  OthersPage,
  PrintingPage,
  CardPrintingPage,
  BrochurePage,
  TshirtPage,
  StickerFlyerPage,
  PolythenePage,
  FLexBannerPage,
  ReceiptInvoicePage,
  PreventivePage,
  CorrectivePage,
  PredictivePage,
  TroubleShootingPage,
  ProgrammingPage,
  WebTechPage,
  SoftwarePage,
} from "./Pages";
import {  MainLayout } from "./Layouts";

const Routes = () => (
  <Switch>
    <RouteWithLayout
     component={HomePage} 
     exact 
     path="/" 
     layout={MainLayout} />
    
    <RouteWithLayout
      component={TeamPage}
      exact
      path="/team"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={AboutPage}
      exact
      path="/about"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={BlogPage}
      exact
      path="/blog"
      layout={MainLayout}
    />

    <RouteWithLayout
      component={ContactPage}
      exact
      path="/contact"
      layout={MainLayout}
    />

    <RouteWithLayout
      component={GalleryPage}
      exact
      path="/gallery"
      layout={MainLayout}
    />

    <RouteWithLayout
      component={ServicesPage}
      exact
      path="/services"
      layout={MainLayout}
    />

    <RouteWithLayout
      component={AccessoriesPage}
      exact
      path="/accessories"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={EdesignPage}
      exact
      path="/design"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={LogoDevPage}
      exact
      path="/design/logo"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={BusinessPage}
      exact
      path="/design/card"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={StickerPage}
      exact
      path="/design/sticker"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={BannerPage}
      exact
      path="/design/banner"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={OthersPage}
      exact
      path="/design/others"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={FlexPage}
      exact
      path="/design/flex"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={DigitalBrandPage}
      exact
      path="/digital"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ConsultationPage}
      exact
      path="/consult"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={MaintenancePage}
      exact
      path="/maintenance"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={InternetPage}
      exact
      path="/digital/internet"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={SocialPage}
      exact
      path="/digital/social"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ColorPage}
      exact
      path="/digital/color"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ContentPage}
      exact
      path="/digital/content"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ClothingPage }
      exact
      path="/digital/cloth"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={SystemAnaPage }
      exact
      path="/consult/system"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={BusinessAnaPage }
      exact
      path="/consult/business"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={RiskManPage }
      exact
      path="/consult/risk"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={QualityAssPage}
      exact
      path="/consult/quality"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ProjectManPage }
      exact
      path="/consult/project"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={PrintingPage }
      exact
      path="/printing"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={CardPrintingPage }
      exact
      path="/printing/card"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={BrochurePage }
      exact
      path="/printing/brochure"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={TshirtPage}
      exact
      path="/printing/shirt"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={StickerFlyerPage}
      exact
      path="/printing/stickfly"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ReceiptInvoicePage}
      exact
      path="/printing/receipt"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={PolythenePage}
      exact
      path="/printing/polythene"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={FLexBannerPage}
      exact
      path="/printing/flexb"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={PreventivePage}
      exact
      path="/maintenance/prevent"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={CorrectivePage}
      exact
      path="/maintenance/correct"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={PredictivePage}
      exact
      path="/maintenance/predict"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={TroubleShootingPage}
      exact
      path="/maintenance/trouble"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={ProgrammingPage}
      exact
      path="/program"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={WebTechPage}
      exact
      path="/program/webtech"
      layout={MainLayout}
    />
    <RouteWithLayout
      component={SoftwarePage}
      exact
      path="/program/software"
      layout={MainLayout}
    />
    <Redirect to="/not-found" />
  </Switch>
);
export default Routes;
